[project]
name = "flow"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sergey Mikhno <sergey.mikhno@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tasks]

[dependencies]
numpy = "1.24.4.*"
cython = ">=3.0.10,<3.1"
pip = ">=24.0,<25"
python = "3.11.*"


[pypi-dependencies]
buildozer = "~=1.5.0"
